### PR TITLE
Fix attendance date format bug

### LINKED ISSUE #403: Mark and delete attendance format not following UG specification
The mark and delete attendance date accepts the format yyyy-M-d even though UG in v1.5 specified that yyyy-MM-dd is the only correct format

### PR DESCRIPTION
**Pull request by tansanchian**
closes #403

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -116,6 +116,9 @@ public static Date parseDate(String date) throws ParseException {
         try {
             SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
             format.setLenient(false);
+            if (!date.matches("\\d{4}-\\d{2}-\\d{2}")) {
+                throw new ParseException("Invalid date-time format. Expected format: yyyy-MM-dd");
+            }
```
Comment (waihongteh) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:121]: Good to see that invalid dates like 2024-1-11 is not allowed!

**Review by waihongteh — APPROVED** [review]
LGTM!
