### PR TITLE
Solve bug on student selection

### LINKED ISSUE #216: Delete Stu Student profile still show
image

### PR DESCRIPTION
**Pull request by waihongteh**
If the student selected is deleted, the profile will be set to empty and the selection will be cleared.
Closes #216

### CODE REVIEW

File: src/main/java/seedu/address/ui/StudentListPanel.java [hunk 1]
```diff
@@ -28,6 +29,12 @@ public StudentListPanel(ObservableList<Student> studentList, StudentProfile stud
         this.studentProfile = studentProfile;
         studentListView.setItems(studentList);
         studentListView.setCellFactory(listView -> new StudentListViewCell());
+        DeleteCommand.getStudentProperty().addListener((observable, oldValue, newValue) -> {
+            if (StudentProfile.isSameStudent(newValue)) {
+                studentProfile.setStudent(null);
+                studentListView.getSelectionModel().clearSelection();
```
Comment (tansanchian) [inline src/main/java/seedu/address/ui/StudentListPanel.java:35]: Good job on spotting this!

**Review by tansanchian — APPROVED** [review]
LGTM!
