### PR TITLE
Refine add command 

### LINKED ISSUE #154: Add Student bug
image
The displayed text for incorrect format has 3 issues:
1. A followed by ... sounds a bit weird as A does not appear as a special character but rather as a something. Perhaps can phrase it as "A" or alphabet "A".
2. "digits and" instead of "digitsand".
3.  "...should not start and end with spaces". Is this necessary? In the parser we should have trimmed the ID right?

### LINKED ISSUE #160: Add Command bug, same name but different student id
image

Add Command bug, same name but different student id, expected behaviour is to add the student in. 
Instead it shows duplicate error.

### LINKED ISSUE #189: Change add command to addStu command

### PR DESCRIPTION
**Pull request by SamsonChew**
closes #154 
closes #189
closes #160

### CODE REVIEW

File: src/test/java/seedu/address/logic/LogicManagerTest.java [hunk 1]
```diff
@@ -195,9 +195,9 @@ public void saveAddressBook(ReadOnlyAddressBook addressBook, Path filePath)
     public void execute_storageThrowsIoExceptionOnSaveTutorials_throwsCommandException() {
         // Create a dummy IOException to be thrown when saving tutorials
         IOException dummyIoException = new IOException("Invalid command format! \n"
-                + "add: Adds a student to the tutorial book. Parameters: n/NAME s/STUDENT_ID "
+                + "addStu: Adds a student to the tutorial book. Parameters: n/NAME s/STUDENT_ID "
                 + "[c/TUTORIAL_CLASS] \n"
-                + "Example: add n/Samson s/A1234567X c/T1001");
+                + "Example: addStu n/Samson s/A1234567X c/T1001");
```
Comment (tansanchian) [inline src/test/java/seedu/address/logic/LogicManagerTest.java:200]: Good to see that a more intuitive command word is used!

**Review by tansanchian — APPROVED** [review]
LGTM!
