### PR TITLE
Fix empty assignment issue

### LINKED ISSUE #367: [PE-D][Tester C] Add Assignment allows titles to be empty
The add assignment allows assignment names/titles to be empty which doesn't make sense in real life.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: apollo-tan/ped#14

### PR DESCRIPTION
**Pull request by waihongteh**
This PR fixes functionality bug as stated in #367. Refer to the comment for the rationale behind why it is a functionality bug if needed.
Closes #367

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java [hunk 1]
```diff
@@ -26,6 +26,13 @@ public void parse_validArgs_returnsMarkAssignmentCommand() throws Exception {
         assertEquals(new UnmarkAssignmentCommand(0, expectedAssignment), command);
     }
 
+    @Test
+    public void parse_emptyTitle_throwsParseException() throws Exception {
+        String userInput = "1 " + PREFIX_NAME;
+
+        assertThrows(ParseException.class, () -> parser.parse(userInput));
```
Comment (tansanchian) [inline src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java:33]: Good to see the new functions are tested in depth!

**Review by tansanchian — APPROVED** [review]
LGTM!
