### PR TITLE
Fix edit bug related to mark attendance

### LINKED ISSUE #378: Mark attendance bug
image

image

Mark attendance -> Attendance student id -> Mark attendance

### PR DESCRIPTION
**Pull request by tansanchian**
closes #378

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -117,6 +117,7 @@ private static Student createEditedStudent(Student studentToEdit, EditStudentDes
         TutorialId updatedTutorialId = editStudentDescriptor.getTutorialId()
                 .orElse(studentToEdit.getTutorialId());
         PresentDates updatedDates = editStudentDescriptor.getPresentDates().orElse(studentToEdit.getPresentDates());
+        updatedDates.setStudentID(studentToEdit.getStudentId(), updatedStudentId);
```
Comment (SamsonChew) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:120]: good to see now studentID all updated to markAtt execution.

**Review by SamsonChew — APPROVED** [review]
