### PR TITLE
Delete feature bug

### LINKED ISSUE #98: Delete student bug
Delete student but student still exist in tutorial class.

### PR DESCRIPTION
**Pull request by Fui03**
Closes #98

### CODE REVIEW

File: src/main/java/seedu/address/model/tut/Tutorial.java [hunk 1]
```diff
@@ -11,182 +11,402 @@
...
+        public void assignStudent(Student student) {
+            requireNonNull(student);
+            students.add(student);
+        }
+
+        @Override
+        public TutName getTutName() {
+            throw new NoTutorialException();
+        }
+
```
Comment (waihongteh) [inline src/main/java/seedu/address/model/tut/Tutorial.java:196]: I'm not sure about the original intention of having get student method here, but I wonder should getting student from the name here be considered invalid? Like should it not throw exception and return the student instead? It doesn't seem to be violating the rules by returning the student.

File: src/test/java/seedu/address/model/tut/TutorialTest.java [hunk 2]
```diff
@@ -175,16 +176,123 @@ public void setAttendance_studentNotInTut_false() {
...
+        assertTrue(NONE.studentInList(ALICE));
+    }
+
+    @Test
+    public void deleteStudent_noneTest() {
+        NONE.add(ALICE);
+        assertTrue(NONE.studentInList(ALICE));
+        NONE.deleteStudent(ALICE);
+        assertFalse(NONE.studentInList(ALICE));
+    }
```
Comment (SamsonChew) [inline src/test/java/seedu/address/model/tut/TutorialTest.java:297]: Comprehensive testing on the latest changes on implementation!! Everything looks good to me!

File: src/main/java/seedu/address/model/tut/Tutorial.java [hunk 3]
```diff
@@ -7,186 +7,363 @@
...
+                }
+                return tutorialClass.equals(exist.tutorialClass);
+            }
+
+            return false;
+        }
+        @Override
+        public String toString() {
+            return tutName + ": Tutorial " + tutorialClass;
+        }
```
Comment (SamsonChew) [inline src/main/java/seedu/address/model/tut/Tutorial.java:367]: Nice reimplementation for Tutorial class to ensure when deleteTut command get executed no null class exception will be thrown

File: src/main/java/seedu/address/model/tut/Tutorial.java [hunk 4]
```diff
@@ -11,182 +11,402 @@
...
+
+        public static None none() {
+            return none;
         }
-        if (!studentInList(student)) {
-            add(student);
+
+        @Override
+        public void add(Student student) {
+            if (student != null && !students.contains(student)) {
```
Comment (waihongteh) [inline src/main/java/seedu/address/model/tut/Tutorial.java]: Maybe using requireNonNull here for student is a better option? If not the student will just not get added and the null error is not thrown.

File: src/main/java/seedu/address/model/tut/Tutorial.java [hunk 5]
```diff
@@ -11,182 +11,402 @@
...
+        }
+
+        @Override
+        public boolean studentInList(Student student) {
+            return students.contains(student);
+        }
+
+        @Override
+        public void deleteStudent(Student student) {
+            students.remove(student);
```
Comment (waihongteh) [inline src/main/java/seedu/address/model/tut/Tutorial.java:340]: Should this method throw studentNotFound exception if the student is not in the list? Just to remind the user in case there is some typo.

File: src/main/java/seedu/address/model/tut/Tutorial.java [hunk 6]
```diff
@@ -11,182 +11,402 @@
...
+            throw new NoTutorialException();
+        }
+
+        @Override
+        public boolean studentInList(Student student) {
+            return students.contains(student);
+        }
+
+        @Override
+        public void deleteStudent(Student student) {
```
Comment (waihongteh) [inline src/main/java/seedu/address/model/tut/Tutorial.java:238]: Should this method throw studentNotFound exception if the student is not in the list? Just to remind the user or programmer in case there is some typo or issues.

File: src/main/java/seedu/address/model/tut/Tutorial.java (hunk 3 above)
Comment (waihongteh) [reply src/main/java/seedu/address/model/tut/Tutorial.java:367]: Yes I do agree! Good job in making use of polymorphism which fits the OOP paradigm.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 7]
```diff
@@ -41,9 +41,7 @@ public AddCommand parse(String args) throws ParseException {
                 : new StudentId("1001");
         TutorialClass tutorialClass = argMultimap.getValue(PREFIX_TUTORIALCLASS).isPresent()
                 ? ParserUtil.parseTutorialClass(argMultimap.getValue(PREFIX_TUTORIALCLASS).get())
-                : new TutorialClass("1001");
-        System.out.println(tutorialClass);
-        System.out.println(studentId);
+                : TutorialClass.of("1001");
```
Comment (Reallyeasy1) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:44]: Good use of TutorialClass.of()

File: src/main/java/seedu/address/model/student/TutorialClass.java [hunk 8]
```diff
@@ -7,60 +7,106 @@
 import com.fasterxml.jackson.annotation.JsonProperty;
 
 /**
- * Represents a Tutorial class ID in the address book.
- * Guarantees: immutable; is valid as declared in {@link #isValidTutorialClass(String)}
+ * Represents an abstract TutorialClass.
+ * A TutorialClass can either be an existing class with a specific class code or a "None" type.
```
Comment (Reallyeasy1) [inline src/main/java/seedu/address/model/student/TutorialClass.java:11]: Nice javadocs

File: src/main/java/seedu/address/model/ModelManager.java [hunk 9]
```diff
@@ -110,6 +110,10 @@ public boolean hasStudent(Student student) {
     @Override
     public void deleteStudent(Student target) {
         addressBook.removeStudent(target);
+        tutorials.deleteStudent(target);
+        for (Assignment assignment: assignmentList.getAssignments()) {
```
Comment (Reallyeasy1) [inline src/main/java/seedu/address/model/ModelManager.java:114]: maybe assign assignmentList.getAssignments()

File: src/main/java/seedu/address/model/student/TutorialClass.java [hunk 10]
```diff
@@ -7,60 +7,106 @@
...
         }
 
-        TutorialClass otherClass = (TutorialClass) other;
-        return value.equals(otherClass.value);
     }
 
-    @Override
-    public int hashCode() {
-        return value.hashCode();
+    private static final class Exist extends TutorialClass {
```
Comment (Reallyeasy1) [inline src/main/java/seedu/address/model/student/TutorialClass.java:70]: Exist sounds wierd for a tutorialclass that exists, use ExistingClass instead

File: src/main/java/seedu/address/model/tut/Tutorial.java [hunk 11]
```diff
@@ -7,186 +7,371 @@
...
-        return tutName + ": Tutorial " + tutorialClass;
+        @Override
+        public boolean setAttendance(Date date, StudentId target) {
+            requireNonNull(date);
+            requireNonNull(target);
+            TutDate tutDate = tutDates.computeIfAbsent(date, TutDate::new);
+            return students.stream()
+                    .filter(s -> s.getStudentId().equals(target))
+                    .findFirst()
+                    .map(student -> {
```
Comment (Reallyeasy1) [inline src/main/java/seedu/address/model/tut/Tutorial.java:283]: Maybe explain what the functuon chaining does

File: src/main/java/seedu/address/model/tut/exceptions/NoTutorialException.java [hunk 12]
```diff
@@ -0,0 +1,16 @@
...
+ * Signals that the operation cannot proceed because there is no tutorial available.
+ * This exception is thrown when an operation specific to a tutorial is attempted
+ * on a non-existent or "None" tutorial.
+ */
+public class NoTutorialException extends RuntimeException {
+
+    /**
+     * Constructs a new NoTutorialException with a default error message.
+     */
+    public NoTutorialException() {
```
Comment (Reallyeasy1) [inline src/main/java/seedu/address/model/tut/exceptions/NoTutorialException.java:13]: Good job
