### PR TITLE
Resolve edit command

### LINKED ISSUE #168: Edit student bug
{3B50EB57-5DC4-41F3-BA2B-B6FD78ED1717}
{8E04A9CC-45C1-48EB-A762-EE425B83B493}
{5FD96510-8725-4740-9735-B285BFFCDBC8}

After editing the student id, the attendance feature doesn't work as expected. I suspect its the tutorials.json isn't updated.

### PR DESCRIPTION
**Pull request by SamsonChew**
closes #168

### CODE REVIEW

File: src/test/java/seedu/address/model/ModelManagerTest.java [hunk 1]
```diff
@@ -294,4 +295,71 @@ public void equals() {
...
+        Student student = new StudentBuilder().withName("Charlie").withStudentId("A7654321X")
+                .withTutorialId(nonExistentTutorialId.getValue()).build();
+        modelManager.addStudent(student);
+
+        // Attempt to unassign the student from the non-existent tutorial
+        modelManager.unassignStudent(student, nonExistentTutorialId);
+
+        // Verify that no exceptions are thrown and the student's tutorial ID remains unchanged
+        assertEquals(nonExistentTutorialId, student.getTutorialId());
+    }
```
Comment (tansanchian) [inline src/test/java/seedu/address/model/ModelManagerTest.java:364]: Those are some test cases with really high coverage. Good job!

**Review by tansanchian — APPROVED** [review]
LGTM!
