### PR TITLE
Debug delete tutorial command

### LINKED ISSUE #379: Delete tutorial functional bug
The `tutorial.json` file does not update the student’s tutorial ID to reflect an "empty class" after deleting the tutorial. This is a functional bug because, after a tutorial is deleted, any student previously assigned to it should show an "empty class" as their tutorial ID, not a different tutorial ID or leftover ID from the deleted class. This is not a feature flaw but rather a debugging fix for the unexpected behavior of the `deleteTut` command.

The change corrects the behavior so that deleted tutorials are properly removed from students' records, aligning with the intended functionality without altering the feature itself.

image

### PR DESCRIPTION
**Pull request by Fui03**
This is a functional bug, not feature flaw. The explanation is given in #379.
Closes #379

### CODE REVIEW

File: src/main/java/seedu/address/model/tut/TutorialList.java [hunk 1]
```diff
@@ -90,11 +94,31 @@ public String deleteTutorial(Tutorial tutorial) {
...
+
+        Name updatedName = editStudentDescriptor.getName().orElse(studentToEdit.getName());
+        StudentId updatedStudentId = editStudentDescriptor.getStudentId().orElse(studentToEdit.getStudentId());
+        TutorialId updatedTutorialId = editStudentDescriptor.getTutorialId()
+                .orElse(studentToEdit.getTutorialId());
+        PresentDates updatedDates = editStudentDescriptor.getPresentDates().orElse(studentToEdit.getPresentDates());
+
+        return new Student(updatedName, updatedStudentId, updatedTutorialId, updatedDates);
+    }
+
```
Comment (SamsonChew) [inline src/main/java/seedu/address/model/tut/TutorialList.java:121]: looks the tutorial.json file will get updated after the command.

**Review by SamsonChew — APPROVED** [review]
