### PR TITLE
Fix bug on student attendance

### LINKED ISSUE #106: Implement Unmark Attendance

### PR DESCRIPTION
**Pull request by tansanchian**
closes #106

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/UnattendCommand.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+     *
+     * @param studentId The ID of the student to be marked absent.
+     * @param tutorialClass The tutorial class the student is enrolled in.
+     * @param tutDate The date on which the student is marked absent.
+     */
+    public UnattendCommand(StudentId studentId, TutorialId tutorialClass, Date tutDate) {
+        requireNonNull(studentId);
+        requireNonNull(tutorialClass);
+        requireNonNull(tutDate);
+        this.studentId = studentId;
```
Comment (SamsonChew) [inline src/main/java/seedu/address/logic/commands/UnattendCommand.java:49]: I like how you ensure all fields are required to be filled before the command execute successfully
