### PR TITLE
Fix Attend Command Bugs

### LINKED ISSUE #147: Attend tutorial bug
An invalid month, date, or year was provided, but the command still accepts the date.
image
image
image

### LINKED ISSUE #149: Absent command
image
The wording is misleading, as it suggests there's a list tracking students who are absent.

### LINKED ISSUE #158: Attend command display issue
image
"Tutorial Class doesn't exist or Student not in Tutorial Class!"
The above feedback displayed has 2 issues:
1. Class and Student are both in capital letter which is incorrect
2. Word choice for "student not in tutorial class" can be modified to "the student has no tutorial assigned" to sound grammatically correct and more understandable.

### LINKED ISSUE #161: Attend invalid student id error message
image

Attend invalid student id error message is invalid, did not add space

### LINKED ISSUE #164: Different date time format for addAsg and attend command
The date time format for addAsg and attend command is different. Would be good to standardise the date time format.
image

image

### LINKED ISSUE #165: Wrong date time format shown by the error message in the attend command
image

Prior to this, I have added students and class T9999 into the application.

image

Keying in a command of the same format will give me 0009/06/15, which is not a valid date.

### LINKED ISSUE #167: Misleading error message for deleteAtt command
{53B6AFBC-79A2-4C6D-A7DD-68504E676E99}
Should display 'Deleted attendance' instead of 'Mark absent'.

### LINKED ISSUE #178: Error on deleteAtt command
Seem like deleteAtt command is not working or which command is the correct command?

Screenshot 2024-10-27 at 5 13 21 PM
Screenshot 2024-10-27 at 5 13 31 PM

### PR DESCRIPTION
**Pull request by tansanchian**
closes #147 
closes #149 
closes #158 
closes #161 
closes #164 
closes #165
closes #167 
closes #178

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -110,13 +110,14 @@ public static TutorialId parseTutorialId(String tutorialId) throws ParseExceptio
      */
     public static Date parseDate(String date) throws ParseException {
         try {
-            return new SimpleDateFormat("yyyy/MM/dd").parse(date);
+            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
+            format.setLenient(false);
+            return format.parse(date);
```
Comment (waihongteh) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:115]: Good to see that new standard format with strict mode is adapted! Well done!

**Review by waihongteh — APPROVED** [review]
LGTM!

File: src/test/java/seedu/address/logic/parser/AddressBookParserTest.java [hunk 2]
```diff
@@ -88,13 +88,13 @@ public void parseCommand_absent() throws Exception {
         String userInput = UnattendCommand.COMMAND_WORD + " "
                 + PREFIX_STUDENTID + "A1001000U "
                 + PREFIX_TUTORIALID + "T1001 "
-                + PREFIX_ATTENDANCEDATE + "2024/02/21";
+                + PREFIX_ATTENDANCEDATE + "2024-02-21";
```
Comment (SamsonChew) [inline src/test/java/seedu/address/logic/parser/AddressBookParserTest.java:91]: Good to see all formats are aligned now

**Review by SamsonChew — APPROVED** [review]
